name: wat2watch
description: OTT content recommendation CLI application
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

#dependencies:
#  dotenv: ^4.1.0
#  dart: '>=3.0.0 <4.0.0'
#  args: ^2.4.2
#  http: ^1.1.0
#  json_annotation: ^4.8.1
#  crypto: ^3.0.3
#  sqflite: ^2.3.0
#  path: ^1.8.3
#  console: ^4.1.0
#  mongo_dart: ^0.8.4

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  mongo_dart: ^0.8.4
  uuid: ^3.0.6
  crypto: ^3.0.1
  http: ^0.13.6

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.3